services:
  db_postgres:
    build: ../postgres
    volumes:
      - "${HOST_PG_HOME:?err}:/var/lib/postgresql/data/pgdata"
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - "POSTGRES_USER=${PG_USER:?err}"
      - "POSTGRES_PASSWORD=${PG_PASS:?err}"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
      - "SERVICE_NAME=postgres"
      - "SERVICE_5432_CHECK_TCP=true"
      - "SERVICE_5432_CHECK_INTERVAL=15s"
      - "SERVICE_5432_CHECK_TIMEOUT=3s"

